# ======== STAGE 1 — BUILD ========
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ======== STAGE 2 — RUN ========
FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY src/ src/
ENV PORT=3000
CMD ["src/index.js"]

